### ISSUE TITLE
extra_port_mappings error

### ISSUE THREAD

**Issue by luis-sousa-pinto** [tehcyx/terraform-provider-kind#45]
Hi,

Using this terraform script I always get an error

terraform {
  required_providers {
    kind = {
      source = "tehcyx/kind"
      version = "0.2.0"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.14.0"
    }
  }
}

provider "kind" {}

resource "kind_cluster" "default" {
  name = "cluster-2"
  node_image = "kindest/node:v1.25.3"
  wait_for_ready = true
  
  
  kind_config {
    kind = "Cluster"
    api_version = "kind.x-k8s.io/v1alpha4"

    node {
      role = "control-plane"

      kubeadm_config_patches = [
        "kind: InitConfiguration\nnodeRegistration:\n  kubeletExtraArgs:\n    node-labels: \"ingress-ready=true\"\n"
      ]

      extra_port_mappings {
        container_port = 80
        host_port = 80
      }
      extra_port_mappings {
        container_port = 443
        host_port = 443
      }
    }

    node {
      role = "worker"      
    }

    node {
      role = "worker"
    }

    node {
      role = "worker"
    }
  }
}

This is terraform plan:

Terraform will perform the following actions:

  # kind_cluster.default will be created
  + resource "kind_cluster" "default" {
      + client_certificate     = (known after apply)
      + client_key             = (known after apply)
      + cluster_ca_certificate = (known after apply)
      + completed              = (known after apply)
      + endpoint               = (known after apply)
      + id                     = (known after apply)
      + kubeconfig             = (known after apply)
      + kubeconfig_path        = (known after apply)
      + name                   = "cluster-2"
      + node_image             = "kindest/node:v1.25.3"
      + wait_for_ready         = true

      + kind_config {
          + api_version = "kind.x-k8s.io/v1alpha4"
          + kind        = "Cluster"

          + node {
              + kubeadm_config_patches = [
                  + <<-EOT
                        kind: InitConfiguration
                        nodeRegistration:
                          kubeletExtraArgs:
                            node-labels: "ingress-ready=true"
                    EOT,
                ]
              + role                   = "control-plane"

              + extra_port_mappings {
                  + container_port = 80
                  + host_port      = 80
                }
              + extra_port_mappings {
                  + container_port = 443
                  + host_port      = 443
                }
            }
          + node {
              + role = "worker"
            }
          + node {
              + role = "worker"
            }
          + node {
              + role = "worker"
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

and this is the error:

kind_cluster.default: Creating...
╷
│ Error: command "docker run --name cluster-2-control-plane --hostname cluster-2-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro -e KIND_EXPERIMENTAL_CONTAINERD_SNAPSHOTTER --detach --tty --label io.x-k8s.kind.cluster=cluster-2 --net kind --restart=on-failure:1 --init=false --cgroupns=private --publish=0.0.0.0:80:80/TCP --publish=0.0.0.0:443:443/TCP --publish=127.0.0.1:58842:6443/TCP -e KUBECONFIG=/etc/kubernetes/admin.conf kindest/node:v1.25.3" failed with error: exit status 125
│ 
│   with kind_cluster.default,
│   on main.tf line 16, in resource "kind_cluster" "default":
│   16: resource "kind_cluster" "default" {
│ 
╵

Can you help?

**Comment by luis-sousa-pinto** [comment]
if I remove the extra_port_mappings it works

**Comment by luis-sousa-pinto** [comment]
figure out the problem

**Comment by matthias-hampel** [comment]
Could you figure out what the problem with the `extra_port_mappings` property is?
Why can't the kind cluster get created when using the property?

**Comment by oleksii-donoha** [comment]
for anyone stumbling across this: if you're running a rootless podman or docker, it might not have enough permissions to bind a port in <1024 range.
