### ISSUE TITLE
kube_proxy_mode value

### ISSUE THREAD

**Issue by maabik** [tehcyx/terraform-provider-kind#46]
Hi All !
I would like the cluster not to install kube-proxy. But when kube_proxy_mode has "none" or "false", the cluster install kube-proxy.
What to be done. Thanks in advanced.

_kube-system          kube-proxy-2br7s                                1/1     Running   0          22m
kube-system          kube-proxy-85z7r                                1/1     Running   0          22m
kube-system          kube-proxy-bdmbq                                1/1     Running   0          22m
kube-system          kube-proxy-l9kwb                                1/1     Running   0          22m
kube-system          kube-proxy-wmk62                                1/1     Running   0          22m_

**Comment by tehcyx** [comment]
Hi @maabik ,
I'll have to check. It could be that the configuration is not exposed (yet). I'll update the issue here once I had a chance to look at the code.

**Comment by tehcyx** [comment]
https://github.com/tehcyx/terraform-provider-kind/releases/tag/v0.2.1 we have a new release that solves this issue.

Try this configuration:
```hcl
terraform {
  required_providers {
    kind = {
      source  = "tehcyx/kind"
      version = "~> 0.2.1"
    }
  }
}

provider "kind" {
}

resource "kind_cluster" "default" {
  name = "new-cluster"
  wait_for_ready = true
  kind_config {
    kind = "Cluster"
    api_version = "kind.x-k8s.io/v1alpha4"

    networking {
      kube_proxy_mode = "none"
    }

    node {
      role = "control-plane"
    }
  }
}
```

Should give this output
```sh
$ kubectl get pods -A
NAMESPACE            NAME                                                READY   STATUS    RESTARTS   AGE
kube-system          coredns-5d78c9869d-cprck                            0/1     Running   0          14s
kube-system          coredns-5d78c9869d-zt988                            0/1     Running   0          13s
kube-system          etcd-new-cluster-control-plane                      1/1     Running   0          25s
kube-system          kindnet-74nqv                                       1/1     Running   0          14s
kube-system          kube-apiserver-new-cluster-control-plane            1/1     Running   0          25s
kube-system          kube-controller-manager-new-cluster-control-plane   1/1     Running   0          25s
kube-system          kube-scheduler-new-cluster-control-plane            1/1     Running   0          25s
local-path-storage   local-path-provisioner-6bc4bddd6b-tcqtf             1/1     Running   0          13s
```

if you encounter any issue with this, please feel free to open another issue.
