### ISSUE TITLE
extraMounts

### ISSUE THREAD

**Issue by flashpixx** [tehcyx/terraform-provider-kind#66]
Hello,

how can I specify the `extraMounts` in the TF configuration see https://kind.sigs.k8s.io/docs/user/configuration#extra-mounts ?

**Comment by tehcyx** [comment]
You'll have to add it to the node config and it has the same options as the extra mount config in kind: https://github.com/tehcyx/terraform-provider-kind/blob/f7796fb0fa1fe8f5c35cd3c7785162c779c6a526/kind/schema_kind_config.go#L165-L188

```
resource "kind_cluster" "default" {
  name = "new-cluster"
  wait_for_ready = true
  kind_config {
    kind = "Cluster"
    api_version = "kind.x-k8s.io/v1alpha4"

    node {
      role = "control-plane"
      extra_mounts {
        host_path = "/path/to/my/other-files/"
        container_path = "/other-files"
        read_only = true
        selinux_relabel = false
        propagation = "None"
      }
    }
  }
}
```

**Comment by tehcyx** [comment]
Closing this for now, please reopen if you have any further questions.

**Comment by flashpixx** [comment]
Thanks a lot
