### ISSUE TITLE
networking ip_family not honored

### ISSUE THREAD

**Issue by bdalpe** [tehcyx/terraform-provider-kind#69]
When attempting to create a dual-stack cluster, the provider does not honor the ipFamily setting (no errors displayed).

```terraform
resource "kind_cluster" "this" {
  name           = "example"
  wait_for_ready = true

  kind_config {
    api_version = "kind.x-k8s.io/v1alpha4"
    kind        = "Cluster"

    networking {
      ip_family = "dual"
    }

    node {
      role  = "control-plane"
      image = "kindest/node:v1.31.0" 

      # ...
    }
  }
}
```

Setting the equivalent config on my machine and running the commands manually succeeds in starting a dual-stack cluster:

```bash
kind create cluster --config - <<EOT
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: dual
EOT
```

**Comment by devaughnsaxa** [comment]
Indeed, it seems the code only accepts ipv4 or ipv6 but not dual yet.
https://github.com/tehcyx/terraform-provider-kind/blob/19d69e19cabb866d7f622f80ecfd52778fef6fbf/kind/structure_kind_config.go#L143-L151

**Comment by tehcyx** [comment]
I just created a new release with the change and a kind upgrade: https://github.com/tehcyx/terraform-provider-kind/releases/tag/v0.7.0

Thanks again for the contribution and bringing this up here.
